; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny1604]
platform = atmelmegaavr
board = ATtiny1604
framework = arduino
upload_protocol = serialupdi
upload_speed = 115200
;10 MHz / 8 MHz: Internal RC oscillator (typical for 3.3V systems).
;Highest speeds (20 MHz) require a minimum of 4.5V for maximum reliability, particularly for programming.
board_build.f_cpu = 10000000L
